/// <reference types="expo/types" />

// NOTE: This file should not be edited. It is generated by Expo and references the ambient types
// (env vars, CSS/CSS-module imports, assets) used by the app. It is gitignored.
